### ISSUE TITLE
`ctx.command.get_param_by_name()` not recognized by mypy

### ISSUE THREAD

**Issue by ghost** [janluke/cloup#105]
#### Bug description
Even if I annotate my context variables as `ctx: cloup.Context`, mypy does not recognize the existence of `ctx.command.get_param_by_name()`:
```
error| "Command" has no attribute "get_param_by_name"  [attr-defined]
```

#### To Reproduce
Minimal example:
```py
import cloup                            
                                        
                                        
def foo(ctx: cloup.Context):            
    ctx.command.get_param_by_name("bar")
```

#### Environment
* Python 3.10.1
* click 8.0.3
* cloup 0.12.1
* mypy 0.931

**Comment by janluke** [comment]
Thank you for taking time to report this :) This works as expected though:
- `get_param_by_name` is a method of `ConstraintMixin`
- `ctx.command` could be a `cloup.Group`, which doesn't include `ConstraintMixin`.

In the future, I may include option groups and constraints in `BaseCommand`, then I could declare `ctx.command` as `BaseCommand`. For now, if you are sure `ctx.command` will have the method you can either `cast(ctx.command, cloup.Command)` or nest that in `if isinstance(ctx.command, cloup.Command)` (or `ConstraintMixin`).
