### ISSUE TITLE
A section for positional arguments

### ISSUE THREAD

**Issue by janluke** [janluke/cloup#106]
As we know:
> [click.argument()](https://click.palletsprojects.com/en/8.0.x/api/#click.argument) does not take a help parameter. This is to follow the general convention of Unix tools of using arguments for only the most necessary things, and to document them in the command help text by referring to them by name.

Personally:
- I think there's no reason to prevent a user from showing a section for positional arguments. 
- People used to argparse CLIs often don't even look at the usage string or the command description and expect to see a "Required arguments" as a first section.
- I don't like when an arguable convention is forced on me.
- Even if I agree that positional arguments should be mentioned in the command description, I think it doesn't hurt to have a (redundant) section where each argument is described shortly. Especially if the developer can decide when to show it up.

## Plan (need to check if it's easy/possible)

- Define a cloup.Argument class that extends click.Argument.
- Add help argument to cloup.argument.
- Show a "Positional arguments" section if at least one argument (of the command) has a non-empty help description.

Feedback appreciated. @jsonvillanueva @kdeldycke

**Comment by kdeldycke** [comment]
> it doesn't hurt to have a (redundant) section where each argument is described shortly.

This 👆. 100%.
