### ISSUE TITLE
 Read arguments with error

### ISSUE THREAD

**Issue by tower-town** [janluke/cloup#107]
```python
# test.py
from cloup import command,option

@command()
@option('-n','--name',help='input your name')

def printName(name):
    print(f"your name is {name}")

if __name__ == "__main__":
    printName()
```

`python test.py -name`

output it:
`your name is  ame`

I think there input arguments is error, but it no warning.

**Comment by janluke** [comment]
Not a bug. This is how GNU-style short flags work, you don't need a space between `-n` and a value. To use the long option, you have to write `--name`, not `-name`.

**Comment by janluke** [comment]
The following are all equivalent:
```
-n Casey
-n=Casey
-nCasey
```
