### ISSUE TITLE
`SectionMixin`: `super().__init__` should be called at the beginning of `__init__`

### ISSUE THREAD

**Issue by janluke** [janluke/cloup#118]
... it's necessary to set `self.chain` before the rest of the code runs — otherwise you can get an error about the `chain` attribute not existing, in some cases.

_Originally posted by @alexreg in https://github.com/janluke/cloup/pull/116#discussion_r873250465_

**Comment by alexreg** [comment]
@janluke Just curious, is there anything in particular you are worried about with moving `super().__init__` to the beginning? Or just being cautious?

**Comment by alexreg** [comment]
A more conservative fix would be to leave it where it is and add at the beginning of `__init__` the following.
```python
self.chain = kwargs.get("chain", None)
del kwargs["chain"]
```

It seems like a bit of a kludge though. Overall, I noticed that re Cloup types, sometimes you are calling `super().__init__` at the start, sometimes at the end, and at least once somewhere in the middle.

**Comment by janluke** [comment]
> @janluke Just curious, is there anything in particular you are worried about with moving super().__init__ to the beginning? Or just being cautious?

Just being cautious. I don't remember why I put the super() call at the end. Moving the call at the beginning is probably something safe to do. Still, "formally" it deserves to be its own PR because if someone who used `SectionMixin` directly may have relied on this. Pragmatically, very few people (if any) use these mixins directly, so it's just a formality.

**Comment by alexreg** [comment]
@janluke Makes sense. Want me to create a PR?

**Comment by janluke** [comment]
It'd be great! Thanks :)
