### ISSUE TITLE
Require one constraint prevents subcommand help from working

### ISSUE THREAD

**Issue by ryancausey** [janluke/cloup#129]
#### Bug description
If I create a command group that has an option group with the `require_one` constraint, and then add a subcommand to that group, I am unable to run `--help` on the subcommand without passing one of the required options at the group level.

#### To Reproduce
```python
# test.py
import cloup
from cloup.constraints import require_one


@cloup.group()
@cloup.option_group(
    "credentials",
    cloup.option("--foo", help="foo"),
    cloup.option("--bar", help="bar"),
    constraint=require_one,
)
def cli(foo, bar):
    "Top level group text."


@cli.command()
def subcommand():
    """Subcommand help text."""


if __name__ == "__main__":
    cli()
```
```bash
python test.py subcommand --help
```

#### Expected behavior
Help text of subcommand is printed:

```
python test.py subcommand --help
Usage: test.py subcommand [OPTIONS]

  Subcommand help text.

Options:
  --help  Show this message and exit.
```

#### Actual behavior
An error is printed due to one of the required group options not being specified.

```
python test.py subcommand --help
Usage: test.py [OPTIONS] COMMAND [ARGS]...
Try 'test.py --help' for help.

Error: exactly 1 of the following parameters must be set:
  --foo
  --bar
```

**Comment by janluke** [comment]
Thanks for the detailed report. I'll check if I can do something about this as soon as I can. Meanwhile, I want to suggest you an alternative, which is in my opinion more flexible and future-proof. My suggestion is to move the group arguments, especially if required, to the subcommands. This if more flexible since if tomorrow you want to add a command that doesn't require those credentials, you will be able to do it.

```python
import cloup
from cloup.constraints import require_one


class Common:
    credentials = cloup.option_group(
        "credentials",
        cloup.option("--foo", help="foo"),
        cloup.option("--bar", help="bar"),
        constraint=require_one,
    )


@cloup.group()
def cli():
    """Top level group text."""
    pass


@cli.command()
@Common.credentials
def subcommand(foo, bar):
    """Subcommand help text."""


if __name__ == "__main__":
    cli()
```

**Comment by ryancausey** [comment]
That's a smart idea. I didn't think about giving the decorator a name and re-using it. Thanks!

**Comment by janluke** [comment]
Btw, Click has the same problem with required Group parameters:
```python
import click

@click.group()
@click.option("--foo", help="foo", required=True)
def cli(foo):
    """Top level group text."""

@cli.command()
def subcommand():
    """Subcommand help text."""

if __name__ == "__main__":
    cli("subcommand --help".split())
```

I think required parameters at the Group level should probably be avoided.

**Comment by ryancausey** [comment]
So if this is a Click issue then, should this be closed?

**Comment by janluke** [comment]
No, the Cloup part is solvable and I'm going to push the fix.
