### ISSUE TITLE
Consider renaming __constraints to __cloup_constraints__

### ISSUE THREAD

**Issue by pocek** [janluke/cloup#131]
Please consider renaming `__constraints` to `__cloup_constraints__`. Although at first it may sound like bikeshedding, they are valid reasons to do so:

1. In classes, names like `__name__` don't get mangled, but names like `__name` do (as described in https://docs.python.org/3/reference/expressions.html#private-name-mangling). It matters if you decorate a callback with a (callable) class, not just a function. And, if you do that, accessing `__constraints` for reasons like copying/moving them into another object gets tricky, because it's _private_. It's still possible though, but one has to use setattr/getattr/delattr family of functions instead of simple attribute access and `del`.

2. It would be similar to what click does with `__click_params__`. With `__click_params__`, one can simply and happily copy/move them without resorting to setattr/getattr/delattr method.

3. The name would be clearer - it's not obvious what `__constraints` are. I believe `__cloup_constraints__` is simply a better name.

**Comment by janluke** [comment]
Did this cause an actual problem to you? If yes, I'd be interested in reading an example.

**Comment by janluke** [comment]
> one can simply and happily copy/move them without resorting to setattr/getattr/delattr method.

I think I named it `__constraints` exactly to communicate that this is private API. But I think I'm okay with the change you're proposing. Do you want to open a PR?

**Comment by pocek** [comment]
> Did this cause an actual problem to you? If yes, I'd be interested in reading an example.

Yes, it's a real problem I have encountered in a construct like this:

```python
import cloup
from cloup.constraints import mutually_exclusive

class ClassBasedDecorator:
    def __init__(self, func):
        self.func = func

        # Standard attributes used by click
        self.__name__ = func.__name__
        self.__doc__ = func.__doc__

        if hasattr(func, '__click_params__'):
            self.__click_params__ = func.__click_params__
            del func.__click_params__

        # Cloup makes it harder
        if hasattr(func, '__constraints'):
            setattr(self, '__constraints',  getattr(func, '__constraints'))
            delattr(func, '__constraints')

    def __call__(self, *args, **kwargs):
        return self.func(*args, **kwargs)

@cloup.command(show_constraints=True)
@ClassBasedDecorator
@cloup.option('--foo')
@cloup.option('--bar')
@cloup.constraint(mutually_exclusive, ['foo', 'bar'])
def hello(foo, bar):
    """Hello"""
    print('hello')

hello()
```

I hope it doesn't look too unconventional - to have the decorators ordered like this, but this is **the** way that makes sense in my application.

> Do you want to open a PR?

OK, I can to that.

**Comment by janluke** [comment]
> Yes, it's a real problem I have encountered in a construct like this. [...] I hope it doesn't look too unconventional - to have the decorators ordered like this, but this is the way that makes sense in my application.

The construct was already clear but I was curious about the real use case which requires you to mess with `__constraints`. Anyway, it's fine, don't feel obliged to share the details. I'll wait for the PR :)
