### ISSUE TITLE
Rename `sorted` attribute of `Section` to `is_sorted` to solve conflict with `Section.sorted` static method

### ISSUE THREAD

**Issue by alexreg** [janluke/cloup#140]
Mypy seems to give one type-checking error (on the master branch).

```
cloup/_sections.py:68: error: Function "Callable[[str, Union[Iterable[Command], Dict[str, Command]]], Section]" could always be true in boolean context  [truthy-function]
```

This evidently arises because `Section` has both an instance variable named `sorted` (a bool) and a class method named `sorted` too. I very much think it would be worth renaming one of these variables, since it's only going to create confusion and type-checking complications. (You're already having to use `type: ignore` marker in the constructor.)

**Comment by alexreg** [comment]
Sorry about the duplicate issues; the GitHub website was having issues yesterday!

**Comment by janluke** [comment]
If we rename the `sorted` attribute to, say, `is_sorted`, we need to bump the major version. I've already a 1.1 milestone, maybe we can just use type: ignore for now and reserve this for next 2.0 release.

**Comment by janluke** [comment]
Nah, let's just have 2.0 as next release.

**Comment by janluke** [comment]
In fact, we already renamed `__constraints`. Even if I consider it private API, someone could have used it anyway.

**Comment by alexreg** [comment]
@janluke Yeah. I noticed that with `__constraints` -> `__cloup_constraints__` (and good to see). Anyway, I agree that renaming the attribute to `is_sorted` is likely the best way to solve this conflict.

**Comment by janluke** [comment]
Do you want to open a PR for this?
