### ISSUE TITLE
Styling of aliases

### ISSUE THREAD

**Issue by wabiloo** [janluke/cloup#151]
I would like to be able to style the aliases differently, in particular in the list of commands appearing in a group.

Currently, aliases appear in brackets behind the main command name, and in the same color.
When there are several, and long ones, it is not hugely readable.

<img width="571" alt="Screenshot 2023-04-22 at 20 45 58" src="https://user-images.githubusercontent.com/4056263/233803619-2e089131-684b-405e-a47d-aeb5306d5644.png">

I would like to at least be able to choose a different color for them

**Comment by janluke** [comment]
You need to override `format_subcommand_aliases` to fully customize how aliases are formatted. For colours, please check out the following PR (feedback appreciated):
- #152
