### ISSUE TITLE
Over-highlighting of heading's extra space

### ISSUE THREAD

**Issue by kdeldycke** [janluke/cloup#157]
#### Bug description

The space separating the `Usage:` header from the CLI name and argument schema is highlighted as if it was part of the heading.

#### To Reproduce

Given the following minimal Cloup CLI:
```python
from cloup import HelpFormatter, HelpTheme, Context, command, Style, Color

SETTINGS = Context.settings(
    formatter_settings=HelpFormatter.settings(
        theme=HelpTheme(
            heading=Style(fg=Color.bright_blue, bold=True, underline=True),
        )
    )
)

@command(context_settings=SETTINGS)
def cli():
    pass

if __name__ == '__main__':
    cli()
```

If I run this with the latest version of Cloup, I get the following help screen:

<img width="359" alt="Screenshot 2023-06-03 at 10 19 18" src="https://github.com/janluke/cloup/assets/159718/40ea5e0d-3b68-4a67-bd28-30a7c6ee1b69">

#### Expected behavior

Instead, I expect the first line of the help screen renders like this:

<img width="363" alt="Screenshot 2023-06-03 at 10 24 23" src="https://github.com/janluke/cloup/assets/159718/4f43a20d-7bb5-421b-9a05-8fd44aac2dd6">

Notice how the space after `Usage:` is not underlined.

I.e. the first line should not produce:
```python
"\x1b[94m\x1b[1m\x1b[4mUsage: \x1b[0mcloup_heading_highlight.py [OPTIONS]"
```
But:
```python
"\x1b[94m\x1b[1m\x1b[4mUsage:\x1b[0m cloup_heading_highlight.py [OPTIONS]"
```

**Comment by janluke** [comment]
Thanks for reporting!

**Comment by kdeldycke** [comment]
Thanks @janluke for the quick fix!
