### ISSUE TITLE
Change `HelpTheme` type to allow sub-classing

### ISSUE THREAD

**Issue by kdeldycke** [janluke/cloup#159]
In Click Extra, I have a [default theme lying around](https://github.com/kdeldycke/click-extra/blob/5245748ef30f0a2fba2a7899530c203445907c49/click_extra/colorize.py#L48) that try to extends `cloup.HelpTheme` with additional categories of styles. Like [log-level colors](https://github.com/kdeldycke/click-extra/blob/5245748ef30f0a2fba2a7899530c203445907c49/click_extra/colorize.py#L75-L80) and [other help screen details](https://github.com/kdeldycke/click-extra/blob/5245748ef30f0a2fba2a7899530c203445907c49/click_extra/colorize.py#L82-L92).

The problem is that `cloup.HelpTheme` is a `NamedTuple`. And I cannot easily sub-class it. [As you can see in my code](https://github.com/kdeldycke/click-extra/blob/5245748ef30f0a2fba2a7899530c203445907c49/click_extra/colorize.py#L48), I had to redefine the whole properties and methods.

I also encountered issues with [MyPy which cannot solve references to sub-styles](https://github.com/kdeldycke/click-extra/blob/5245748ef30f0a2fba2a7899530c203445907c49/click_extra/version.py#L66-L67):
```pytb
click_extra/version.py:58: error: Cannot determine type of "default_theme"  [has-type]
        default_package_name_style: IStyle | None = default_theme.invoked_command
                                                    ^~~~~~~~~~~~~
click_extra/version.py:59: error: Cannot determine type of "default_theme"  [has-type]
        default_prog_name_style: IStyle | None = default_theme.invoked_command
                                                 ^~~~~~~~~~~~~
```

That is somewhat expected, as [`NamedTuple` subclasses is flagged as `wontfix` by Python's `typing` project](https://github.com/python/typing/issues/427).

@janluke, would you be open to change the type of `HelpTheme` so I can reuse it seamlessly?

I naively think that a class is the natural choice, but maybe a `@dataclass` might be another alternative to `NamedTuple`. I'm pretty sure you have a better idea of what `HelpTheme` should look like in that case.

**Comment by janluke** [comment]
Weird I used a NamedTuple for HelpTheme. Whatever was my reasoning, it was a bad idea. I'll have a look when I have time.

**Comment by janluke** [comment]
I'll fix this next later today. I'll probably have to bump the major version for this.

**Comment by kdeldycke** [comment]
Thanks @janluke for this refactor! 💪
