### ISSUE TITLE
Protocol to automatically set `param.required` based on constraints applied?

### ISSUE THREAD

**Issue by mathrick** [janluke/cloup#183]
I'm working on a CLI with multiple, dynamic sources of defaults and pretty complicated rules for what parameters are required when, so I was pretty excited to discover Cloup's constraints. However, I was disappointed to realise that it only errors out when parameters are not provided, but doesn't participate at all in determining whether parameters are `required` from Click's perspective. This is unfortunate, since I also use the prompt mechanism to show the user the computed default and get missing required parameters for a better UI if running in the interactive mode, as there are a lot of parameters to study otherwise. With constraints as they currently exist, I still have to write all the custom logic to make sure things know when they are required and when to prompt, essentially duplicating it all.

I'm not 100% sure this is on the right track, but I think it should be possible to repurpose most of the existing constraints so that they can answer the question of "is this parameter required, according to my rules?", by basing them around a new method, `is_required()`:

```python
class Constraint:
    def is_required(self, param: click.Parameter, ctx: click.Context) -> bool:
        "Return whether param is required, based on the current state of ctx and this constraints logic"
        ...

    def check_values(self, params, ctx):
        return all(param_value_is_set(p, ctx.params[p.name])
                   for p in params if self.is_required(p, ctx))
```
As an example, for `require_all`, the result would always be `True` for parameters it applies to. For `If`, the result would depend on whether the condition is currently satisfied, and would then forward to the corrent branch's constraint.

A somewhat trickier part is making `Option.required`  use the appropriate constraint's `is_required()`, so the determination can be made using this new protocol. I'm not currently familiar enough with the internals of Cloup and Click to have a proper sense of how hard that would be. The overarching goal though is to make constraints augment the otherwise static boolean value, so that other mechanisms which look at it could work transparently from the single source of truth and not require me to encode the requirements in multiple places.

Obviously, there are still constraint that can't be fully expressed using this protocol, such as `require_none`, and those would just return `False` always and continue to use their existing implementation of `check_values()`.

**Comment by mathrick** [comment]
Alright, so I've been staring at this problem for a while now and clearly managed to confuse myself along the way. There is not really any built-in interaction between `prompt` and `required` in Click, so apologies for the confusion there. I do think, however, that it would still be useful to have a protocol that with `is_required()` and possibly also `is_allowed()`, so that intelligent decisions about things like prompting could be built with it.

**Comment by janluke** [comment]
I'm closing this. If you have a more concrete proposal, feel free to open another issue.
