### ISSUE TITLE
Help theme constraint=Style(fg=Color.xxx) is ignored

### ISSUE THREAD

**Issue by hiwixxl** [janluke/cloup#85]
Please, make sure you are using the last version of Cloup before
opening a bug report.
Version 0.11.0

#### Bug description
In help constraint is always printed with col1 style.

**Comment by janluke** [comment]
Can you add a minimal reproducible example? Thank you.

**Comment by hiwixxl** [comment]
After experimenting with different constraints I found out that this option is for the help line:
"option_group": [at least 1 required]
I used only:
Constraints:
  {-a, -b, -c}  mutually exclusive
That line has col1 style for {-a, -b, -c}.
Please close this case.
