### ISSUE TITLE
Should I drop support for click 7.x before v1.0?

### ISSUE THREAD

**Issue by janluke** [janluke/cloup#87]
Click 8 has been out for a while now and I have little motivation to support both Click 7 and 8.
Pros of dropping support:
- can remove the code handling click 7
- can use new Click features (e.g. ParameterSource) without bothering
- can halve the tests.

**Comment by kdeldycke** [comment]
Maintaining open-source software is hard enough. And it's not like you're basing your library on bleeding-edge or unmaintained packages. Click 8.x is out, actively maintained and stable. So feel free to get rid of Click 7.x if it simplify your maintainership! 😉

**Comment by janluke** [comment]
Support for Click 7 was dropped.
