### ISSUE TITLE
Add loading of options from a TOML configuration file

### ISSUE THREAD

**Issue by kdeldycke** [janluke/cloup#96]
I'd like to propose the addition of a feature that will add some configuration file loading facilities.

I developed some reusable generic code for my [`meta-package-manager` CLI](https://github.com/kdeldycke/meta-package-manager) that parse a TOML file and load up its content right into the structure defined by the CLI option schema.

This code is available at: https://github.com/kdeldycke/meta-package-manager/blob/develop/meta_package_manager/config.py

With some effort I'm pretty sure it can be added as a generic feature to `cloup`. What's your opinion @janluke?

**Comment by janluke** [comment]
I actually want this feature (though I prefer YAML) in practically all my CLIs. I know there are various Click extensions for configuration files but I've never tried one. Have you tried any of those? What's your impression?

I think I need to evaluate these existing libraries and see if I see limitations before adding this feature to Cloup. There's a chance I'll arrive to a conclusion soon because I need this feature at work too.

**Comment by kdeldycke** [comment]
YAML is as great as TOML for this use case. As you said it is a matter of preferences.

For the context, I choose TOML for the simple reason it was already a dependency of my CLI. If you agree to add configuration in Cloup, it shouldn't be hard to support both, with a set of optional dependencies (like `pip install cloup[yaml]` and `pip install cloup[toml]`) if you'd like to keep a lean package.

As for existing librairies:
* [`click-configfile`](https://github.com/click-contrib/click-configfile): part of the semi-official `click-contrib` organization. It is [abandoned (last commit from 2017)](https://github.com/click-contrib/click-configfile/issues/9). Does not allow for [exclusion of some options](https://github.com/click-contrib/click-configfile/issues/8). The configuration schema definition looks cumbersome.
* [`click_config_file`](https://github.com/phha/click_config_file): has not seen a commit for a year. Seems easy to use (good defaults). Proper handling of resolution order. Support for multi value options, multiple options or a combination of both.

**Comment by janluke** [comment]
It makes sense to include this feature in Cloup if and only if it needs some sort of integration with the rest (command classes). But, as far as I can tell now, I think this feature can be implemented without any need of integration from Cloup part. Am I wrong? 

It'd be interesting to know also why you developed your own solution rather than using (or forking) `click_config_file`.

If this is not added to Cloup we could work together to a new library. But at the moment I've very little time for open-source.

**Comment by kdeldycke** [comment]
The reason I proposed to add it to Cloup is because Cloup seemed actively maintained and its implementation is way cleaner than `click_config_file` (I'm impressed by the full type hinting BTW).

I also had a vague idea that the extra-care around option management in Cloup (because of its additional constraint support) will provide bullet-proof introspection to bridge the gap between `default_map` and the config file tree-structure. I find that approach developer-friendly compared to the cumbersome schema-definition of `click_config_file`.

Resource-limitation is the dark-secret of open-source. Nobody (and I include myself) really have time to invest. It still quite a miracle any of us are able to produce public code! 😉

That being said, instead of creating a new library or contributing to Cloup, there might be a third way which is to take over `click_config_file` and revive interest in it.

**Comment by kdeldycke** [comment]
For the record, I ended up implementing TOML configuration file as a standalone utility in [`click-extra`](https://github.com/kdeldycke/click-extra). I plan to [implement YAML parsing later](https://github.com/kdeldycke/click-extra/issues/13).

**Comment by kdeldycke** [comment]
> I actually want this feature (though I prefer YAML)

Good news, I just implemented YAML config support in [`click-extra`](https://github.com/kdeldycke/click-extra) (https://github.com/kdeldycke/click-extra/commit/c594fb846307753453ac08cdb3ff3af0779ab292).

**Comment by janluke** [comment]
Thank you, @kdeldycke!

**Comment by janluke** [comment]
I'm closing this for now. I'm currently not convinced that this should be added to Cloup. People who look for this feature has several solutions available, including @kdeldycke's one and [click_config_file](https://github.com/phha/click_config_file). Nonetheless, if your app need complex configuration, there are certainly other interesting solutions like [Hydra](https://hydra.cc/docs/intro/).
